name: test

on: push

jobs:
  mix_test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - pair:
              elixir: 1.14.0
              otp: 24.3
            lint: lint
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Fetch Dependencies
        run: mix deps.get --only test

      - name: Compile project
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Check formatting
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Run test suite
        run: mix test || if [[ $? = 2 ]]; then mix test --failed; else false; fi
